### ISSUE TITLE
[Feature Request] Allowing to specify names and locations of "data", "executable", and "results" folders

### ISSUE THREAD

**Issue by zhiyuli** [cybergis/job-supervisor#20]
- allow model contributor/developer to specify names and locations of "data", "executable", and "results" folders: for example developer could specify all the 3 parts to point to one folder "run", in which case all data and code and results will be stored in the same folder "run" inside the container. 
{
"data": "/run",
"executable: "/run",
"results": "/run"
}

- Compute keeps using "data", "executable", and "results" folders as default settings if user does not specify them;
- 
- with the special case above (all in "run" folder), globus will download everything in the folder "run" back to jupyter. so it is better to allow user to specify what specific files and folder to be downloaded, this could be a list of specific file/folder names or "regex-alike" pattern strings to filter the filesystem (like glob: https://docs.python.org/3/library/glob.html ), such as ["streamflow.*.nc", "landsurface*.nc"]. By default, globus just downloads the whole "results" folder if user does not specify anything.

{
"data": "/run",
"executable: "/run",
"results": "/run",
"results_list": ["streamflow.*.nc", "landsurface*.nc", "*.txt"]
}

**Comment by alexandermichels** [comment]
This should be possible through the /folder/:folderId route here: https://github.com/cybergis/cybergis-compute-core/blob/v2/server.ts#L567

Using requests, I was able to do it:

> response = put("/folder/1666299253EqDMB", body={'name': 'test'})
print(response.status_code)
print(response.content)

Responses:

>200
b'{"id":"1666299253EqDMB","name":"test","hpc":"keeling_community","hpcPath":"/data/keeling/a/cigi-gisolve/scratch/1666299253EqDMB","globusPath":"/1666299253EqDMB","userId":"alexandermichels@cybergisx.cigi.illinois.edu","isWritable":false,"createdAt":"2022-10-20T20:54:14.919Z","updatedAt":null,"deletedAt":null}'

Screenshot from the database:
![image](https://user-images.githubusercontent.com/36479843/205167213-a39e7e49-f889-41b1-b25a-fe8a2cf82d37.png)

We will do some further testing on our end, but this seems to be an SDK issue.

**Comment by alexandermichels** [comment]
Issue seems to be abandoned, we can reopen if this need still exists.
