### ISSUE TITLE
[feature_request] add model name to job folder name 

### ISSUE THREAD

**Issue by zhiyuli** [cybergis/job-supervisor#23]
currently job folder name is just random string. it is hard to tell what model it is from the job folder name, giving troubles when inspecting things on HPC.

Propose to add model name to job folder name: <model>_<jobid>, for example: summa_XXXXXXX
add a new optional field in manifest.json
"job_folder_name_prefix": "summa_"

**Comment by alexandermichels** [comment]
I believe this is solved by https://github.com/cybergis/cybergis-compute-python-sdk/pull/62. We don't have the new manifest option, but that may add unnecessary complexity anyways. We can re-open/open new if this feature needs to be expanded.
