### ISSUE TITLE
[feature request] allow to choose what results (folder) to download and allow to download results from previous model run

### ISSUE THREAD

**Issue by zhiyuli** [cybergis/job-supervisor#24]
currently all files in "results" folder get downloaded,
there is a use case from SUMMA that the model execution step generates a lot of model outputs files,
but most of the time, user just want to know  some statistical indices, such as averaged data.
so this kind of statistical indices  or processed results are calculated in the post-processing step, and get saved to "results" folder.
However, there are some cases users want to get all the raw model outputs back (probably in a separate step) to further analyze the model outputs on jupyter.

So there should be a way to allow user to choose what subfolder(s) in the "results" to download, and allow user to choose to download  other subfolder(s) in "results" in a separate step without re-running the model or submitting a job

**Comment by alexandermichels** [comment]
I believe the first part is satisfied by https://github.com/cybergis/cybergis-compute-hello-world/blob/main/manifest.json#L38, but needs documentation on the SDK site.

The second part was implemented in v2.1
