### ISSUE TITLE
Emit more logs between JOB_INIT and JOB_ENDED

### ISSUE THREAD

**Issue by zhiyuli** [cybergis/job-supervisor#28]
@CarnivalBug 's data fusion model takes up to 1-2 hour to finish. On the SDK UI, there is no feedback to users between JOB_INIT and JOB_ENDED. It is necessary to give users some updates on job status: like Pending, Running, or....
This feature request will affect both Core and SDK

**Comment by alexandermichels** [comment]
This has been solved by v2.1
