### ISSUE TITLE
[Feature Request, Urgent for iGuide] Jupyter Username To Globus User Folder Path Mapping

### ISSUE THREAD

**Issue by zhiyuli** [cybergis/job-supervisor#46]
In current swarm-based deploy, each jupyter user has a personal data folder named after its username. for example, user "drew" has a data folder called "drew". Compute currently follows this assumption in constructing Globus transfer path for Globus endpoint on Jupyter side. However, the assumption does not hold anymore when changing to K8s deploy with a different storageclass for PVC/PV provisioning. For example, a NFS-Client provisioner may create a data folder named "iguide-pvc-drew-[UUID]". Thus, a username-to-folder mapping is required. The current assumption that folder name is identical to username could be thought of as a special case of this mapping.

Short-term solution: 
Since the k8s NFS-Client provisioner embeds username as a substring included in the folder name, like "drew" -- "iguide-pvc-drew-[UUID]", it is possible to do a "search and match" to locate the folder on the endpoint that is supposed to match to the username. 

Globus SDK provides a TransferClient.operation_ls() function to list all items under a path for an endpoint, upon which the "search and match" can be performed: https://globus-sdk-python.readthedocs.io/en/stable/services/transfer.html?highlight=endpoint_search#globus_sdk.TransferClient.operation_ls

To make it a little bit more generalized, each Jupyter instance could provide a Regex pattern template in configs, and Compute fills in dynamic username to the template and performs "search and match" between jupyter username and each folder using the regex until a hit is found. The regex should be provided carefully to avoid potential incorrect mappings, like username: drew and drew_demo should be mapped to different folders.

*Special case and solution*: since jupyter username should be unique already, not sure if K8s NFS-Client provisioner could remove [UUID] from the folder name and just keep "iguide-pvc-drew". if so, Compute can directly construct folder name by appending prefix and suffix (read from per jupyter instance configs) to jupyter username.

Long-term:
TBD
Data folder name could be completely different from Jupyter username where simple "search and match" would not work; 
Or other more complicated cases.

**Comment by rkalyanapurdue** [comment]
The NFS subdir provisioner we use for IGUIDE seems to support override of the pattern used to specify the NFS folder path to be created for PVs: https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner

Will test the use of **pathPattern** to have folder match iguide-_\<username\>_

**Comment by zhiyuli** [comment]
From @rkalyanapurdue 

if you need to convert the username returned by the hub rest API, you can use: escapism.escape('[rkalyana@purdue.edu](mailto:rkalyana@purdue.edu)',escape_char='-',safe=set(string.ascii_lowercase + string.digits)) ; essentially the Jhub KubeSpawner is doing this to make sure kubernetes resources have valid names

**Comment by rkalyanapurdue** [comment]
for more details: 

https://jupyterhub-kubespawner.readthedocs.io/en/latest/spawner.html#kubespawner.KubeSpawner.pod_name_template 

https://github.com/jupyterhub/kubespawner/blob/4c1d30634519a58a68c6407a8c2e4557c6d0d9af/kubespawner/spawner.py#L1836

**Comment by zhiyuli** [comment]
example folders created by k8s NFS provisioned on NFS server

iguide-claim-rkalyana-40purdue-2eedu
iguide-claim-zhiyul-40illinois-2eedu

**Comment by zhiyuli** [comment]
@zimo-xiao 
I tested out the codes below and it works
```
#  ------------ Get jupyter username from hub rest api --------------
import requests
token = "XXXXXXXXXX"
r = requests.get("https://www.iguide.geoedf.org/hub/api/user",
                 headers={"Authorization": "token {}".format(token)})
print(r.status_code)
print(r.json())
username = r.json()["name"]


#------------------- jupyter username mapping function for iguide deploy-------------
import string
import escapism  # need to install by conda or pip
username_encoded = escapism.escape(username,
                                  escape_char='-',
                                  safe=set(string.ascii_lowercase + string.digits))
username_mapped = "iguide-claim-{}".format(username_encoded)
print(username_mapped)
```

**Comment by zhiyuli** [comment]
@mitkotak 

```
import string
import escapism  # need to install by conda or pip
def username_mapping_iguide_k8s_js2(in_username):
  username_encoded = escapism.escape(username,
                                  escape_char='-',
                                  safe=set(string.ascii_lowercase + string.digits))
  username_mapped = "iguide-claim-{}".format(username_encoded)
  print(username_mapped)
  return username_mapped
```

**Comment by mitkotak** [comment]
Was resolved in https://github.com/cybergis/cybergis-compute-core/pull/52
