### ISSUE TITLE
[Regression] Label globus tasks with compute job id for easy debugging

### ISSUE THREAD

**Issue by zhiyuli** [cybergis/job-supervisor#51]
Each globus task has a label or say task name, and it is important to set the task name to include compute jobid as part of its name for easy identification in debugging. 

Proposed globus task names
Type A
[ComputeJobID]-[RandomNumber] 

or even better to indicate download vs upload:
Type B
upload-[ComputeJobID]-[RandomNumber] 
download-[ComputeJobID]-[RandomNumber] 

This is a regression issue. It worked as described  in Type A with V2 branch 
but it stopped working on refactor branch (merged_branch branch) where globus task name is now a random string not reflecting the underlying compute jobid at all.

**Comment by mitkotak** [comment]
Resolved in #53
