### ISSUE TITLE
data folder not created if model does not require to upload anything

### ISSUE THREAD

**Issue by zhiyuli** [cybergis/job-supervisor#57]
A iguide model developer noticed a change after we deploy current V2 branch (2.1) to production.
His model does not require users to upload any data (in manijest.json there is NO "require_upload_data": true)

Before 2.1 release, the "data" folder was created on HPC anyway. so this users used "data" folder to store something dynamically created by the model.
Since 2.1 release, the data folder is not created any more.
I told this user to use "executable" folder to store the things, and it works now.
But this brings up a back-compatibility issue on other potential models

**Comment by alexandermichels** [comment]
Not sure if this is still an issue, we can re-open if if this is still causing issues.
