### ISSUE TITLE
[Bug] echo usage causing issues with new CVMFS connector

### ISSUE THREAD

**Issue by mitkotak** [cybergis/job-supervisor#69]
## Problem

In [BaseConnector.ts](https://github.com/cybergis/cybergis-compute-core/blob/a0d6d3ad7cfdb1ca67d4d584dab3df7edda283ae/src/connectors/BaseConnector.ts#L441), all of the path variables are written to submission script through echo "".  This helps store the actual paths rather than the path variables. However, the echo infrastructure seems to be failing while adding a new connector which requires declaring variables from our end in addition to the user. Here's an example from CVMFS:

```json
"init_sbatch_script": [
            "# module use /data/cigi/common/cigi-modules",
            "module load gnu/openmpi-4.1.2-gnu-4.8.5",
            "source ~/.bashrc  # this adds the `singcvmfs` executable to the path",
            "export SINGCVMFS_REPOSITORIES=\"grid.cern.ch,cybergis.illinois.edu\"  # required for singcvmfs, specifies repositories",
            "export BASE=$(pwd)",
            "export tmp_path=\"/tmp/cvmfs-$(openssl rand -base64 12)\"",
            "mkdir tmp_path",
            "export MY_BINDS=\"$tmp_path:/tmp/cvmfs,$BASE:/job/executable,$BASE/result:/job/result\""
```

```typescript
cmd = `singcvmfs -s exec -B \$MY_BINDS docker://centos:7 -cip  ${cmd}`;
```

I would expect the batch script to contain something like

```bash
module purge
# module use /data/cigi/common/cigi-modules
module load gnu/openmpi-4.1.2-gnu-4.8.5
source ~/.bashrc  # this adds the  executable to the path
export SINGCVMFS_REPOSITORIES="grid.cern.ch,cybergis.illinois.edu"  # required for singcvmfs, specifies repositories
export BASE="/data/keeling/a/cigi-gisolve/scratch"
export tmp_path="/tmp/cvmfs-tdRdhj3VtggPaxwn"
mkdir $tmp_path
export MY_BINDS="/tmp/cvmfs-tdRdhj3VtggPaxwn:/tmp/cvmfs,/data/keeling/a/cigi-gisolve/scratch:/job/executable,/result:/job/result"

job_id="1668979690cpWiF" user_id="mitak2@cybergisx.cigi.illinois.edu" maintainer="community_contribution" hpc="keeling_community" executable_folder="/job/executable" data_folder="/job/data" result_folder="/job/result" singcvmfs -s exec -B  "/tmp/cvmfs-tdRdhj3VtggPaxwn:/tmp/cvmfs,/data/keeling/a/cigi-gisolve/scratch:/job/executable,/result:/job/result" docker://centos:7 bash -c "cd /job/executable && bash lookaround.sh"
```

but I am unfortunately getting

```bash
module purge
# module use /data/cigi/common/cigi-modules
module load gnu/openmpi-4.1.2-gnu-4.8.5
source ~/.bashrc  # this adds the  executable to the path
export SINGCVMFS_REPOSITORIES="grid.cern.ch,cybergis.illinois.edu"  # required for singcvmfs, specifies repositories
export BASE=/data/keeling/a/cigi-gisolve/scratch
export tmp_path="/tmp/cvmfs-tdRdhj3VtggPaxwn"
mkdir
export MY_BINDS=":/tmp/cvmfs,:/job/executable,/result:/job/result"

job_id="1668979690cpWiF" user_id="mitak2@cybergisx.cigi.illinois.edu" maintainer="community_contribution" hpc="keeling_community" executable_folder="/job/executable" data_folder="/job/data" result_folder="/job/result" singcvmfs -s exec -B  docker://centos:7 bash -c "cd /job/executable && bash lookaround.sh"
```

I have tried replacing `""` with `''` but that ends up unleashing a flood of back slashes everywhere. I tried `printf` as well but that also led to a similar outcome. 

## Solution

There's two potential solutions to this issue:

1) Check if we can insert a quick patch somewhere such that we can generate developer specified paths in batch script codegen.
2) Figure out a way to such that developer variables and the user variables can co-exist in the same environment. This will involve overhauling the slurm submission logic and replacing it with paramiko based slurm script submission.
 - Here's an example of paramiko being used for slurm submission (https://github.com/SvenMarcus/hpc-rocket/blob/a0cf71ebbdc33de8ea46b0f8a4aac5dba91757e7/test/integration/paramiko/test_sshexecutor.py#L31)
 - We will need to create a python-typescript connector similar to the one that we have for globus.

@zimo-xiao Any thoughts on what to do ?

**Comment by alexandermichels** [comment]
@mitkotak Are we satisfied with PR #77 as a solution to this bug or are there still open problems here?

**Comment by mitkotak** [comment]
Yup all good from my side since CVMFS Connector is stable on dev
